import Head from "next/head";
import Image from "next/image";
import cx from "classnames";
import { Layout, Link, Title } from "@/components";
import { WavingHand, ArrowRight } from "@/icons";
import { Roboto_Mono } from "@next/font/google";
import ArticlesList from "@/layout/ArticlesList";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
});

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Hamza Bargaz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-20">
        <div className="flex flex-col">
          <div className="flex items-center mb-20">
            <div className="flex flex-col max-w-lg">
              <Title>
                Hi
                <WavingHand className="w-6 mx-1" />,
              </Title>
              <h1
                className={cx("my-4 text-3xl font-light", robotoMono.className)}
              >
                I&apos;m Hamza Bargaz
              </h1>
              <p className="mb-6 font-light text-xl tracking-wide">
                I&apos;m a frontend developer with experience ranging from
                frontend over backend to mobile development and I have written
                apps with technologies in all of these sections.
              </p>
            </div>
            <div className="flex justify-center w-full">
              <div className="w-52 h-52 rounded-full bg-white" />
            </div>
          </div>
          {/* last articles */}
          <div className="flex items-start mt-20">
            <div className="flex flex-col w-full">
              <div className="flex items-end mb-4 font-serif text-3xl tracking-wide">
                <span>Last</span>
                <span className="text-secondary mx-1">Articles</span>
                <hr className="ml-2 w-full mb-2" />
              </div>
              <ArticlesList />
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}
