import Head from "next/head";
import Image from "next/image";
import cx from "classnames";
import { Layout, Link, Title } from "@/components";
import { WavingHand, ArrowRight } from "@/icons";
import { Roboto_Mono } from "@next/font/google";
import ArticlesList from "@/layout/ArticlesList";
import { avatar } from "../lib/info";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
});

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Hamza Bargaz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-20 pb-20">
        <div className="flex flex-col">
          <div className="grid grid-cols-1 md:grid-cols-3 mb-20">
            <div className="order-2 md:order-1 flex flex-col max-w-lg col-span-1 md:col-span-2">
              <Title>
                Hi
                <WavingHand className="w-6 mx-1" />,
              </Title>
              <h1
                className={cx(
                  "my-4 text-3xl tracking-tighter font-light",
                  robotoMono.className
                )}
              >
                I&apos;m Hamza Bargaz
              </h1>
              <p className="mb-6 font-extralight text-xl tracking-wide">
                I&apos;m a frontend developer with experience ranging from
                frontend over backend to mobile development and I have written
                apps with technologies in all of these sections.
              </p>
            </div>
            <div className="order-1 md:order-2 mb-20 md:mb-0 flex justify-center w-full">
              <div className="w-52 h-52 rounded-full">
                <Image
                  src={avatar}
                  alt="my picture"
                  className="rounded-full w-full h-full object-cover bg-blend-overlay shrink-0"
                />
              </div>
            </div>
          </div>
          {/* last articles */}
          <div className="flex items-start mt-20">
            <div className="flex flex-col w-full">
              <div className="flex items-end mb-4 font-serif text-3xl tracking-wide">
                <span>Last</span>
                <span className="text-secondary mx-1">Articles</span>
                <hr className="ml-2 w-full mb-2" />
              </div>
              <ArticlesList />
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}
