import Head from "next/head";
import Image from "next/image";
import cx from "classnames";
import { Layout, Link } from "@/components";
import { WavingHand, ArrowRight } from "@/icons";
import { Roboto_Mono } from "@next/font/google";

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
});

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Next.js + TypeScript + Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-20">
        <div className="flex flex-col">
          <div className="flex items-center mb-20">
            <div className="flex flex-col max-w-lg">
              <div className="flex items-end mb-">
                <span className="">Hi</span>
                <WavingHand className="w-6 mx-1" />,
                <hr className="ml-2 w-full mb-1" />
              </div>
              <h1
                className={cx("my-4 text-3xl font-light", robotoMono.className)}
              >
                I&apos;m Hamza Bargaz
              </h1>
              <p className="mb-6 font-light text-xl tracking-wide">
                I&apos;m a frontend developer with experience ranging from
                frontend over backend to mobile development and I have written
                apps with technologies in all of these sections.
              </p>
            </div>
            <div className="flex justify-center w-full">
              <div className="w-52 h-52 rounded-full bg-white" />
            </div>
          </div>
          {/* last articles */}
          <div className="flex items-start mt-20">
            <div className="flex flex-col w-full">
              <div className="flex items-end mb-4 font-serif text-3xl tracking-wide">
                <span>Last</span>
                <span className="text-secondary mx-1">Articles</span>
                <hr className="ml-2 w-full mb-2" />
              </div>
              <div className="">
                {blogs.map((node) => (
                  <Link
                    className="flex group py-6 mb-4 border-t-2 first:border-t-0"
                    key={node.slug}
                    href={`/blog/${node.slug}`}
                  >
                    <div className="flex-col">
                      <div className="group-hover:text-secondary text-2xl mb-2">
                        {node.title}
                      </div>
                      <p className="text-lg text-gray-400">{node.excerpt}</p>
                    </div>
                    <div className="flex items-center ml-auto relative">
                      <ArrowRight className="w-12 block group-hover:hidden absolute right-0 top-0" />
                      <div className="transition duration-500 transform opacity-0 group-hover:opacity-100 group-hover:scale-105">
                        <div className="bg-white h-44 w-44 absolute right-0 -top-24" />
                      </div>
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
}

const blogs = [
  {
    slug: "nextjs-typescript-tailwindcss",
    title: "Next.js + TypeScript + Tailwind CSS",
    excerpt:
      "this article is about how to setup a next.js project with typescript and tailwindcss",
  },
  {
    slug: "nextjs-typescript-tailwindcss2",
    title: "Next.js + TypeScript + Tailwind CSS",
    excerpt:
      "this article is about how to setup a next.js project with typescript and tailwindcss",
  },
];
